
/**
* AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* mercredi 7 novembre 2012 16 h 28 CET
*/


// bank.idl
public interface AccountOperations 
{
  void deposit (int amount);
  void withdraw (int amount);
  int balance ();
  String _toString ();
} // interface AccountOperations
