
/**
* Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* mercredi 7 novembre 2012 16 h 28 CET
*/


// bank.idl
public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
