
/**
* Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* lundi 17 décembre 2012 17 h 20 CET
*/


// bank.idl
public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
