
/**
* AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* lundi 17 décembre 2012 17 h 20 CET
*/


// bank.idl
public interface AccountOperations 
{
  String getID ();
  void deposit (int amount);
  void withdraw (int amount);
  int balance ();
  String _toString ();
} // interface AccountOperations
