
/**
* BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* mercredi 7 novembre 2012 16 h 28 CET
*/

public interface BankOperations 
{
  Account create (org.omg.CORBA.IntHolder id);
  void destroy (Account a);
  Account move (Bank old_bank, Account old_account);
  Account lookup (int id);
  String _toString ();
} // interface BankOperations
