
/**
* BankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* mercredi 7 novembre 2012 16 h 28 CET
*/

public final class BankHolder implements org.omg.CORBA.portable.Streamable
{
  public Bank value = null;

  public BankHolder ()
  {
  }

  public BankHolder (Bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankHelper.type ();
  }

}
