
/**
* BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* lundi 17 décembre 2012 17 h 20 CET
*/

public interface BankOperations 
{
  Account create ();
  void destroy (Account a);
  Account move (Bank old_bank, Account old_account);
  Account lookup (String id);
  String _toString ();
} // interface BankOperations
